### ISSUE TITLE
First line indent

### ISSUE THREAD

**Issue by ExplodingDragon** [BigCoke233/textretty.css#1]
You can indent the first line of a paragraph.

如果可以加入首行缩进就好了.

**Comment by BigCoke233** [comment]
Nice idea. I think I can set a class like `.tex-paragraph-indent` and make `<p>` indented under this class.

---

不错的想法。我觉得我可以设置一个 `.tex-paragraph-indent` 这样的 class，让所有 `<p>` 在有这个 class 的容器里缩进。

**Comment by BigCoke233** [comment]
Paragraph indent is out now in the latset release, 1.1.0.
